export const DBT_SKILLS = [
  {
    id: 'wise-mind',
    name: 'Wise Mind',
    category: 'mindfulness',
    what: 'The place where your feelings and your thinking meet.',
    practice: 'Sit still for one minute. Close your eyes. Ask yourself: what does my wise mind say right now? Not just your feelings. Not just your logic. The place in between.',
  },
  {
    id: 'tipp-temperature',
    name: 'TIPP: Temperature',
    category: 'distress-tolerance',
    what: 'Cold changes your body chemistry fast. It tells your nervous system to slow down.',
    practice: 'Splash cold water on your face or hold ice cubes in your hands for 30 seconds. Notice how your body shifts.',
  },
  {
    id: 'tipp-paced-breathing',
    name: 'TIPP: Paced Breathing',
    category: 'distress-tolerance',
    what: 'Slow breathing sends a calm signal to your brain.',
    practice: 'Breathe in for 4 counts. Breathe out for 6 counts. Do this 5 times. Focus only on the counting.',
  },
  {
    id: 'tipp-intense-exercise',
    name: 'TIPP: Intense Exercise',
    category: 'distress-tolerance',
    what: 'Moving your body fast burns off stress chemicals.',
    practice: 'Do 5 minutes of something that gets your heart going. Jumping jacks, fast walking, dancing in your room. Just 5 minutes.',
  },
  {
    id: 'tipp-progressive-relaxation',
    name: 'TIPP: Progressive Relaxation',
    category: 'distress-tolerance',
    what: 'Squeezing and releasing your muscles teaches your body what relaxed feels like.',
    practice: 'Squeeze your fists tight for 5 seconds. Let go. Feel the difference. Now do your shoulders. Then your legs. Work through your whole body.',
  },
  {
    id: 'stop-skill',
    name: 'STOP Skill',
    category: 'distress-tolerance',
    what: 'A way to pause before you react.',
    practice: "Stop what you're doing. Take one breath. Observe — what's happening inside you right now? Then proceed with care.",
  },
  {
    id: 'opposite-action',
    name: 'Opposite Action',
    category: 'emotion-regulation',
    what: 'When your feelings push you one direction, sometimes the helpful move is the other way.',
    practice: "Notice what your feelings say to do. Feeling like hiding? Go sit near someone. Feeling like lashing out? Speak softly. Feeling like giving up? Do one small thing.",
  },
  {
    id: 'radical-acceptance',
    name: 'Radical Acceptance',
    category: 'distress-tolerance',
    what: "Accepting what is — right now — without fighting it. Acceptance doesn't mean liking it.",
    practice: "Say to yourself: 'This is what is right now. I don't have to like it. I just have to stop fighting it for this moment.' Breathe. Let your shoulders drop.",
  },
  {
    id: 'self-soothe-touch',
    name: 'Self-Soothe: Touch',
    category: 'distress-tolerance',
    what: 'Your sense of touch can calm your whole body.',
    practice: 'Find something soft — a blanket, a pet, warm water on your hands. Focus on how it feels for 30 seconds. Let everything else go quiet.',
  },
  {
    id: 'self-soothe-smell',
    name: 'Self-Soothe: Smell',
    category: 'distress-tolerance',
    what: 'Smell connects straight to the emotion center of your brain.',
    practice: 'Light a candle, smell coffee, step outside and breathe deep. Focus on one smell. Let it fill you up.',
  },
  {
    id: 'self-soothe-sight',
    name: 'Self-Soothe: Sight',
    category: 'distress-tolerance',
    what: 'Looking at something beautiful can shift your whole mood.',
    practice: "Look at something beautiful. A photo you love, the sky, your pet's face. Really look at it for 30 seconds. Notice the details.",
  },
  {
    id: 'self-soothe-sound',
    name: 'Self-Soothe: Sound',
    category: 'distress-tolerance',
    what: 'Music and sound can change how your brain feels in minutes.',
    practice: "Put on one song you love. Close your eyes. Just listen. Don't do anything else. Let the sound hold you.",
  },
  {
    id: 'self-soothe-taste',
    name: 'Self-Soothe: Taste',
    category: 'distress-tolerance',
    what: 'Eating slowly and mindfully can ground you in your body.',
    practice: 'Eat one thing slowly. Really taste it. Notice the texture, the temperature, the flavor. Let it be just about that one thing.',
  },
  {
    id: 'observe-describe',
    name: 'Observe and Describe',
    category: 'mindfulness',
    what: "Naming what you feel takes away some of its power.",
    practice: "Say to yourself: 'I notice I feel angry. I notice my chest is tight. I notice my thoughts are racing.' Just notice. Don't judge. Don't fix. Just name it.",
  },
  {
    id: 'check-the-facts',
    name: 'Check the Facts',
    category: 'emotion-regulation',
    what: "Sometimes our feelings don't match what's actually happening.",
    practice: "Ask yourself: What happened? What am I telling myself about it? What are the actual facts? Is there another way to see this?",
  },
  {
    id: 'body-scan',
    name: 'Body Scan',
    category: 'mindfulness',
    what: 'Noticing where you hold tension helps you release it.',
    practice: "Start at your toes. Move up slowly — feet, legs, belly, chest, shoulders, face. Where are you holding tension? Just notice it. You don't have to fix it. Breathe into that spot.",
  },
  {
    id: 'cope-ahead',
    name: 'Cope Ahead',
    category: 'emotion-regulation',
    what: 'Practicing in your mind makes hard things easier when they happen for real.',
    practice: 'Think of something hard coming up this week. Picture yourself handling it well. What skills will you use? Practice it in your mind like a movie.',
  },
  {
    id: 'build-mastery',
    name: 'Build Mastery',
    category: 'emotion-regulation',
    what: 'Doing something that makes you feel capable builds confidence over time.',
    practice: "Do one thing today that makes you feel capable. Even something small. Fold laundry. Finish a task. Train the dogs. Sit with the feeling of 'I did that.'",
  },
  {
    id: 'walking-middle-path',
    name: 'Walking the Middle Path',
    category: 'interpersonal',
    what: 'Two things can be true at the same time.',
    practice: "Think of something you're struggling with. Now say: 'I can be struggling AND making progress. I can love someone AND be hurt by them. Both are real.' Hold both truths.",
  },
  {
    id: 'dear-man',
    name: 'DEAR MAN',
    category: 'interpersonal',
    what: 'A way to ask for what you need clearly and kindly.',
    practice: "Think of something you need from someone. Describe what happened. Express how you feel. Ask for what you need. Stay firm but kind. You deserve to be heard.",
  },
  {
    id: 'distract-accepts',
    name: 'Distract with ACCEPTS',
    category: 'distress-tolerance',
    what: 'When you need to get through a hard moment, distraction is a real skill.',
    practice: 'Pick one: Do an Activity. Contribute (help someone). Compare (to a harder time you survived). Create an opposite Emotion (watch something funny). Push the thought away for now. Think about something else. Use a strong Sensation (ice, loud music).',
  },
  {
    id: 'half-smile',
    name: 'Half-Smile',
    category: 'distress-tolerance',
    what: 'Your face sends signals to your brain. A tiny smile tells your brain things are okay.',
    practice: "Relax your face. Let your jaw go loose. Let your lips turn up just slightly — not a big smile, just a tiny one. Hold it for one minute. Notice what happens inside.",
  },
]
