export const EMOTION_QUADRANTS = [
  {
    id: 'high-unpleasant',
    color: '#E87B7B',
    bg: '#FDECEC',
    label: 'High energy + hard feelings',
    emoji: '🔴',
    emotions: [
      { id: 'angry', label: 'Angry', def: 'Mad about something that happened' },
      { id: 'anxious', label: 'Anxious', def: 'Worried something bad might happen, body feels tight' },
      { id: 'panicked', label: 'Panicked', def: 'Scared and your body is screaming to run or fight' },
      { id: 'frustrated', label: 'Frustrated', def: 'Trying hard but nothing is working' },
      { id: 'irritated', label: 'Irritated', def: 'Little things are bugging you more than usual' },
      { id: 'overwhelmed', label: 'Overwhelmed', def: 'Too much is happening and you can\'t keep up' },
      { id: 'manic', label: 'Manic', def: 'Energy is way too high, thoughts are racing' },
      { id: 'rageful', label: 'Rageful', def: 'So angry it feels like it could explode' },
    ],
  },
  {
    id: 'high-pleasant',
    color: '#F0C050',
    bg: '#FFF8E1',
    label: 'High energy + good feelings',
    emoji: '🟡',
    emotions: [
      { id: 'excited', label: 'Excited', def: 'Looking forward to something, energy is up' },
      { id: 'happy', label: 'Happy', def: 'Things feel good right now' },
      { id: 'hopeful', label: 'Hopeful', def: 'Believing something good can happen' },
      { id: 'energized', label: 'Energized', def: 'Body and mind feel ready to go' },
      { id: 'giddy', label: 'Giddy', def: 'So happy you might laugh or bounce around' },
      { id: 'proud', label: 'Proud', def: 'You did something and it feels good' },
      { id: 'playful', label: 'Playful', def: 'Feeling silly and light, wanting to have fun' },
      { id: 'passionate', label: 'Passionate', def: 'Caring a lot about something in a strong way' },
    ],
  },
  {
    id: 'low-pleasant',
    color: '#6BBF8A',
    bg: '#E6F7EC',
    label: 'Low energy + good feelings',
    emoji: '🟢',
    emotions: [
      { id: 'calm', label: 'Calm', def: 'Quiet inside, nothing feels rushed' },
      { id: 'content', label: 'Content', def: 'Not needing anything right now, just okay' },
      { id: 'safe', label: 'Safe', def: 'Nothing feels scary or dangerous right now' },
      { id: 'peaceful', label: 'Peaceful', def: 'Everything feels still and gentle' },
      { id: 'grateful', label: 'Grateful', def: 'Noticing something good and feeling thankful' },
      { id: 'loved', label: 'Loved', def: 'Feeling like someone cares about you' },
      { id: 'relaxed', label: 'Relaxed', def: 'Body is loose, mind is quiet' },
      { id: 'tender', label: 'Tender', def: 'Feeling soft and open, maybe a little emotional' },
    ],
  },
  {
    id: 'low-unpleasant',
    color: '#6BA8D6',
    bg: '#E8F1FA',
    label: 'Low energy + hard feelings',
    emoji: '🔵',
    emotions: [
      { id: 'sad', label: 'Sad', def: 'Something hurts inside, might want to cry' },
      { id: 'numb', label: 'Numb', def: 'When you can\'t feel anything at all, like your feelings turned off' },
      { id: 'lonely', label: 'Lonely', def: 'Feeling alone, even if people are around' },
      { id: 'ashamed', label: 'Ashamed', def: 'Feeling like something is wrong with you, not just what you did' },
      { id: 'empty', label: 'Empty', def: 'A hollow feeling, like nothing matters' },
      { id: 'hopeless', label: 'Hopeless', def: 'Feeling like things won\'t get better' },
      { id: 'disconnected', label: 'Disconnected', def: 'Feeling far away from yourself or other people' },
      { id: 'grieving', label: 'Grieving', def: 'Hurting because you lost something or someone' },
    ],
  },
]
